service: nestjs-starter-rest-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, "dev"}
  environment:
    APP_ENV: development
    APP_PORT: 3000
    DB_HOST: 0.0.0.0
    DB_PORT: 3306
    DB_NAME: example_db
    DB_USER: root
    DB_PASS: example
    JWT_ACCESS_TOKEN_EXP_IN_SEC: 3600
    JWT_REFRESH_TOKEN_EXP_IN_SEC: 7200
    JWT_PUBLIC_KEY_BASE64: 
    JWT_PRIVATE_KEY_BASE64: 
    DEFAULT_ADMIN_USER_PASSWORD: admin-example
    
plugins:
  - serverless-offline

package:
  exclude:
    - .git/**
    - src/**
    - test/**
    - e2e/**
    - nodemon.json
    - README.md

functions:
  lambda-main:
    handler: dist/src/lambda-main.handler
    events:
      - http:
          cors: true
          path: '/'
          method: any
      - http:
          cors: true
          path: '{proxy+}'
          method: any