name: build

on:
  pull_request:
    branches: [master]

jobs:
  build_pull_request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - name: Run build step
        run: npm run build
